default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "otpio.xcworkspace", scheme: "otpioUITests")
  end

  desc "Upload new build for testing"
  lane :beta do
    
  end

  lane :release do
    increment_build_number
    get_certificates
    get_provisioning_profile(app_identifier: "io.matrixstudios.otpio")
    get_provisioning_profile(app_identifier: "io.matrixstudios.otpio.otpio-today.appex")
    build_app(scheme: "otpio")
    upload_to_app_store
  end
end
